name: "eBUSd Custom"
version: "1.0.0"
slug: "ebusd_custom"
description: "Custom eBUSd Add-on with local CSV configuration"
startup: services
boot: auto

ports:
  8888/tcp: 8888
  9999/tcp: 9999

map:
  - config:rw

options: {}
schema: {}
