name: "eBUSd"
version: "1.0.0"
slug: "ebusd"
description: "eBUSd daemon for Vaillant / atmoTEC exclusiv"
arch:
  - aarch64
  - armv7
  - amd64
startup: services
boot: auto
host_network: true

options: {}
schema: {}

devices:
  - "/dev/ttyUSB0:/dev/ttyUSB0"

map:
  - config:rw

ports:
  8888/tcp: 8888

image: "local/ebusd"
