name: "eBUSd Custom"
version: "1.0.0"
image: "local/ebusd"
slug: "ebusd"
description: "Custom eBUSd Add-on with local CSV configuration"

arch:
  - aarch64
  - armv7
  - amd64
  - i386



startup: services
boot: auto

ports:
  8888/tcp: 8888
  9999/tcp: 9999

map:
  - config:rw

options: {}
schema: {}
